### ISSUE TITLE
SSL error when i try to make an api request

### ISSUE THREAD

**Issue by jorgemorantes-habi** [BeepQuest/api#20]
Hi, since yesterday i can't request the api, when i try i recive the next error

requests.exceptions.SSLError: HTTPSConnectionPool(host='api.beepquest.com', port=443): Max retries exceeded with url: /v1/visit-answers?initialDate=2021-10-26&limit=200&skip=0 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

**Comment by OkuraSt** [comment]
hi @jorgemorantes 
We changed some certificates for our api, it seems that some of our users are experiencing certificate validation errors. Please, depending on the stack your using check for alternatives for bypassing certificate check, as this is a temporary problem that should be fixed in the next hours
